package packets;

public enum RequestType {
    // --- TỪ CLIENT GỬI LÊN SERVER (Requests) ---
    REGISTER_CLIENT_REQUEST,
    UNREGISTER_CLIENT_REQUEST,
    CREATE_AUCTION_REQUEST,
    CANCEL_AUCTION_REQUEST,
    FINISH_AUCTION_REQUEST,
    PLACE_BID_REQUEST,
    HIGHEST_BID_REQUEST,
    AUCTION_ID_REQUEST,

    // --- TỪ SERVER TRẢ VỀ CLIENT (Responses & Confirmations) ---
    REGISTRATION_CONFIRMATION,
    CANCEL_CONFIRMATION,
    BID_CONFIRMATION,
    AUCTION_LIST_RESPONSE,
    AUCTION_DATA_RESPONSE,
    HIGHEST_BID_RESPONSE,
    ERROR_RESPONSE,

    // --- SERVER CHỦ ĐỘNG THÔNG BÁO (Events / Notifications) ---
    AUCTION_UPDATE_EVENT,
    COUNTDOWN_START_EVENT,
    COUNTDOWN_TICK_EVENT,
    WINNER_NOTIFICATION,
    NO_WINNER_NOTIFICATION;
}